version: 2
updates:
- package-ecosystem: composer
  directory: "/"
  schedule:
    interval: monthly
    time: "04:00"
  open-pull-requests-limit: 10
  target-branch: dev2
  ignore:
  - dependency-name: symfony/flex
    versions:
    - 1.11.0
